services:
  arch-mirror:
    image: ghcr.io/mempler/distro-mirror/arch:main
    ports:
      - "20450:80"
    volumes:
      - arch_data:/var/www/arch
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.labels.zone
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - mirror_network

  ubuntu-mirror:
    image: ghcr.io/mempler/distro-mirror/ubuntu:main
    ports:
      - "20451:80"
    volumes:
      - ubuntu_data:/var/www/ubuntu
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.labels.zone
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - mirror_network

volumes:
  arch_data:
  ubuntu_data:

networks:
  mirror_network:
    driver: overlay
