name: Build Docker Images

on:
  push:
    branches: [main, master]
    paths:
      - "arch/**"
      - "ubuntu/**"
      - "docker-compose.yml"
      - ".github/workflows/build-images.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "arch/**"
      - "ubuntu/**"
      - "docker-compose.yml"
      - ".github/workflows/build-images.yml"
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: arch
            platform: linux/amd64, linux/arm64
            runner: ubuntu-24.04

          - name: ubuntu
            platform: linux/amd64, linux/arm64
            runner: ubuntu-24.04

      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ matrix.name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.name }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
